import Foundation

struct QuizQuestion: Identifiable {
    let prompt: String
    let options: [String]
    let answer: Int
    let note: String
    var id: String { prompt }
}

let quizQuestions: [QuizQuestion] = quizA + quizB + quizC + quizD

let quizA: [QuizQuestion] = [
    QuizQuestion(prompt: "What does a sextant actually measure?",
                 options: ["The angle between two objects", "The time at Greenwich",
                           "The ship's speed", "The depth of water"],
                 answer: 0,
                 note: "One angle, from your eye, between the horizon and a body. Everything else is arithmetic."),
    QuizQuestion(prompt: "Your index error is 2.5 minutes on the arc. What do you do with it?",
                 options: ["Subtract 2.5'", "Add 2.5'", "Double it", "Ignore it below 3'"],
                 answer: 0,
                 note: "On the arc means the instrument reads too much, so the error comes off."),
    QuizQuestion(prompt: "Which way is dip always applied?",
                 options: ["Always subtracted", "Always added",
                           "Added below 20°, subtracted above", "It depends on the body"],
                 answer: 0,
                 note: "The visible horizon lies below true level, so every angle measured from it is too large."),
    QuizQuestion(prompt: "Your height of eye is 16 metres. Roughly what is the dip?",
                 options: ["About 7 minutes", "About 16 minutes", "About 2 minutes", "About 28 minutes"],
                 answer: 0,
                 note: "1.76 times the square root of 16 is 1.76 times 4, which is just over 7 minutes."),
    QuizQuestion(prompt: "Where is refraction largest?",
                 options: ["Near the horizon", "Near the zenith", "At 45 degrees", "It is constant"],
                 answer: 0,
                 note: "Low light passes through a long slant of thick air. At 5 degrees it exceeds 8 minutes."),
    QuizQuestion(prompt: "You bring the Sun's lower limb down. What happens to the semi-diameter?",
                 options: ["It is added", "It is subtracted", "It is halved", "It does not apply"],
                 answer: 0,
                 note: "The lower edge sits below the centre, so the centre is higher: add 16 minutes."),
    QuizQuestion(prompt: "One minute of arc of intercept equals how much distance?",
                 options: ["One nautical mile", "One kilometre",
                           "One degree of longitude", "Sixty nautical miles"],
                 answer: 0,
                 note: "This equivalence is the reason the whole method is workable with a pencil."),
    QuizQuestion(prompt: "Ho is greater than Hc. Which way do you step off the intercept?",
                 options: ["Toward the body", "Away from the body",
                           "North", "It cannot be determined"],
                 answer: 0,
                 note: "A greater altitude means you are nearer the body's geographical position."),
]

let quizB: [QuizQuestion] = [
    QuizQuestion(prompt: "What does a single sight give you?",
                 options: ["A circle of position", "A latitude", "A longitude", "A fix"],
                 answer: 0,
                 note: "Everyone measuring that altitude at that moment stands on one circle round the body's geographical position."),
    QuizQuestion(prompt: "Why is the line of position drawn straight?",
                 options: ["Over a few miles the huge circle is indistinguishable from a line",
                           "Because circles cannot be drawn on charts",
                           "Because the Earth is treated as flat",
                           "Because Mercator charts distort circles"],
                 answer: 0,
                 note: "The circle can be thousands of miles across, so the piece near you is effectively straight."),
    QuizQuestion(prompt: "How fast does the Earth turn in degrees of longitude?",
                 options: ["15 degrees an hour", "1 degree an hour",
                           "360 degrees an hour", "60 degrees an hour"],
                 answer: 0,
                 note: "Three hundred and sixty degrees in twenty-four hours: one degree every four minutes."),
    QuizQuestion(prompt: "Four seconds of chronometer error costs you roughly how much at the equator?",
                 options: ["One nautical mile", "Four nautical miles",
                           "Fifteen nautical miles", "Nothing measurable"],
                 answer: 0,
                 note: "One minute of arc is four seconds of time, and one minute of arc is one mile."),
    QuizQuestion(prompt: "Why did ships carry three chronometers rather than two?",
                 options: ["Two that disagree cannot say which is wrong",
                           "One was always kept unwound as a spare",
                           "Regulations required it", "To measure three time zones"],
                 answer: 0,
                 note: "Three lets the odd one out be identified. Two only tells you there is a problem."),
    QuizQuestion(prompt: "What is a noon sight used for?",
                 options: ["Latitude, without needing the time", "Longitude, without needing tables",
                           "Compass error", "Speed through the water"],
                 answer: 0,
                 note: "At meridian passage the Sun's altitude gives latitude directly from the declination."),
    QuizQuestion(prompt: "Why does swinging the arc matter?",
                 options: ["The true altitude is the lowest reading of the swing",
                           "It warms the mirrors", "It settles the index error",
                           "It cancels refraction"],
                 answer: 0,
                 note: "A tilted sextant measures a slant, which is always larger than the true vertical angle."),
    QuizQuestion(prompt: "Three lines of position form a triangle. What should you do?",
                 options: ["Accept it and place the fix inside", "Take them all again",
                           "Discard the longest line", "Move one line until they meet"],
                 answer: 0,
                 note: "They always form a triangle. Its size is an honest measure of your work."),
]

let quizC: [QuizQuestion] = [
    QuizQuestion(prompt: "Why are star sights only possible in twilight?",
                 options: ["Both the stars and the horizon must be visible",
                           "Stars are brightest then", "Refraction is least then",
                           "The chronometer is checked then"],
                 answer: 0,
                 note: "In full darkness the sea line disappears, and there is nothing to measure from."),
    QuizQuestion(prompt: "How far apart in bearing should three chosen stars ideally be?",
                 options: ["About 120 degrees", "About 30 degrees",
                           "About 180 degrees", "As close together as possible"],
                 answer: 0,
                 note: "Widely spread bodies give position lines that cross at strong angles."),
    QuizQuestion(prompt: "Which star gives latitude almost directly in the northern hemisphere?",
                 options: ["Polaris", "Sirius", "Vega", "Arcturus"],
                 answer: 0,
                 note: "It stands within a degree of the pole, so its altitude is very nearly your latitude."),
    QuizQuestion(prompt: "How do you find the south celestial pole?",
                 options: ["Extend the long axis of the Southern Cross about four and a half times",
                           "Find the brightest southern star",
                           "Follow Orion's belt southward",
                           "Use the Magellanic Clouds' midpoint"],
                 answer: 0,
                 note: "There is no southern pole star. The Cross points at an empty place."),
    QuizQuestion(prompt: "Which pair of stars are the Pointers?",
                 options: ["Dubhe and Merak in the Plough", "Castor and Pollux",
                           "Betelgeuse and Rigel", "Vega and Altair"],
                 answer: 0,
                 note: "The outer two stars of the Plough's bowl, carried five times their spacing, reach Polaris."),
    QuizQuestion(prompt: "How can you tell a planet from a star at a glance?",
                 options: ["A planet shines steadily, a star twinkles", "A planet is always red",
                           "A planet is always brighter", "A planet never rises in the east"],
                 answer: 0,
                 note: "A star is a point and its light is broken up by the air. A disc is not so easily disturbed."),
    QuizQuestion(prompt: "Why is a body near the zenith a good sight?",
                 options: ["Its light passes through the least air, so refraction is smallest",
                           "It is easiest to hold in the mirror",
                           "It needs no index correction",
                           "Its azimuth is easiest to compute"],
                 answer: 0,
                 note: "High sights are honest sights. Low sights need caution and several repeats."),
    QuizQuestion(prompt: "Below roughly what altitude should sights be treated with suspicion?",
                 options: ["15 degrees", "45 degrees", "60 degrees", "5 degrees"],
                 answer: 0,
                 note: "Below fifteen degrees refraction becomes large and dependent on conditions the tables cannot know."),
]

let quizD: [QuizQuestion] = [
    QuizQuestion(prompt: "What is the assumed position for?",
                 options: ["A convenient starting point from which Hc is calculated",
                           "The ship's last known fix", "The destination port",
                           "The body's geographical position"],
                 answer: 0,
                 note: "It is a deliberate guess, chosen for easy arithmetic, and the intercept corrects it."),
    QuizQuestion(prompt: "What does a station pointer do?",
                 options: ["Fixes position from two horizontal angles between three charted marks",
                           "Measures the Sun's altitude", "Keeps Greenwich time",
                           "Records course and speed through a watch"],
                 answer: 0,
                 note: "Coastal work, no sky required, and accurate to yards rather than miles."),
    QuizQuestion(prompt: "What did the traverse board record?",
                 options: ["Course and speed at each half hour of a watch",
                           "The depth of water", "The ship's latitude",
                           "The rate of the chronometer"],
                 answer: 0,
                 note: "Pegs in holes, so a crew who could not write could still hand over an accurate watch."),
    QuizQuestion(prompt: "What is the lead line armed with tallow for?",
                 options: ["To bring up a sample of the bottom", "To make it sink faster",
                           "To stop the line rotting", "To make it visible at night"],
                 answer: 0,
                 note: "Sand, shell or mud in the hollow tells you which bank you are on when the depth alone will not."),
    QuizQuestion(prompt: "Why was the backstaff an improvement on the cross-staff?",
                 options: ["The observer keeps their back to the Sun",
                           "It could measure more than 90 degrees",
                           "It floated if dropped", "It needed no horizon"],
                 answer: 0,
                 note: "John Davis's design saved a great many navigators' eyes."),
    QuizQuestion(prompt: "What made the sextant workable on a moving deck?",
                 options: ["Body and horizon reach the eye together, so both move as one",
                           "Its heavy brass frame damps the roll",
                           "The telescope magnifies the horizon",
                           "Gimbals hold the arc level"],
                 answer: 0,
                 note: "Double reflection is the whole secret. A fixed instrument cannot do it."),
    QuizQuestion(prompt: "What does the pelorus have that a magnetic compass does not?",
                 options: ["No magnetism at all, so the ship's iron cannot affect it",
                           "A built-in chronometer", "A telescope", "A gyroscope"],
                 answer: 0,
                 note: "A dumb compass only knows what you set on it, which is why it can be trusted."),
    QuizQuestion(prompt: "A running fix is only as good as what?",
                 options: ["The dead reckoning between the two sights",
                           "The brightness of the bodies", "The height of eye",
                           "The chart's scale"],
                 answer: 0,
                 note: "Current, leeway and steering errors in the interval all go straight into the answer."),
]
