import Foundation

struct VoyageDay {
    let title: String
    let narration: String
    let seeds: [Int]
}

struct Voyage: Identifiable {
    let slug: String
    let name: String
    let subtitle: String
    let era: String
    let miles: Int
    let opening: String
    let arrival: String
    let days: [VoyageDay]

    var id: String { slug }
    var chartPlate: String { "chart_" + slug }
    var vignettePlate: String { "vig_" + slug }
}

func daySeeds(_ base: Int) -> [Int] { [base, base + 37, base + 74] }

let voyages: [Voyage] = voyagesA + voyagesB

let voyagesA: [Voyage] = [
    Voyage(slug: "trades", name: "The Trade Wind Crossing",
           subtitle: "Tenerife to Barbados", era: "1827", miles: 2760,
           opening: "Three weeks of steady wind on the quarter and nothing to look at but water. The old road west, and the one on which a navigator is most likely to grow careless.",
           arrival: "The island came up green and low, exactly where the last three fixes said it would. Nobody on deck said anything about it, which is the highest praise a landfall ever gets.",
           days: [
            VoyageDay(title: "Day 1 — Out of the roadstead",
                      narration: "The Peak is still astern and there is land to check yourself against. Take your sights now, while a mistake is only embarrassing.",
                      seeds: daySeeds(101)),
            VoyageDay(title: "Day 4 — The wind settles",
                      narration: "The north-east trade has come in properly and the ship has not touched a brace in a day. Steady deck, hard horizon: no excuses.",
                      seeds: daySeeds(104)),
            VoyageDay(title: "Day 7 — A long swell",
                      narration: "A swell has come up from the north-west, out of some weather you will never see. The horizon breathes. Mark it as it passes the mean and not before.",
                      seeds: daySeeds(107)),
            VoyageDay(title: "Day 11 — Dust in the air",
                      narration: "The sky has gone the colour of weak tea. Sand off the African coast, a thousand miles behind. The horizon is soft and every sight tonight will be worth a little less.",
                      seeds: daySeeds(111)),
            VoyageDay(title: "Day 15 — Halfway and no marks",
                      narration: "Nothing has been seen but flying fish for nine days. The chart shows a pencil line and a row of dots, and every one of those dots is an act of faith in your own arithmetic.",
                      seeds: daySeeds(115)),
            VoyageDay(title: "Day 19 — The glass falls",
                      narration: "The barometer has dropped a tenth since morning. Take what the sky will give you while it is still giving.",
                      seeds: daySeeds(119)),
            VoyageDay(title: "Day 22 — Weed and birds",
                      narration: "Sargassum on the water and a bird that does not belong to the deep ocean. Land is somewhere ahead. Now the fixes stop being an exercise.",
                      seeds: daySeeds(122)),
            VoyageDay(title: "Day 24 — Making the landfall",
                      narration: "By the reckoning, Barbados lies under forty miles to the west. Get this one right and you raise it at dawn. Get it wrong by twenty miles and you are past it in the night.",
                      seeds: daySeeds(124)),
           ]),

    Voyage(slug: "horn", name: "Round the Horn",
           subtitle: "Valparaiso to Port Stanley", era: "1852", miles: 1980,
           opening: "South until the butter freezes, then east. The worst water in the world and the one place where a wrong position is not an inconvenience but an ending.",
           arrival: "Stanley harbour, and the ship still in one piece. Down here the fix is not a matter of pride. It is the difference between a harbour and a lee shore.",
           days: [
            VoyageDay(title: "Day 1 — Down the coast",
                      narration: "The Chilean coast to port and the whole of the Pacific to starboard. Twilight is long at this latitude, which is the only kindness the south will offer.",
                      seeds: daySeeds(201)),
            VoyageDay(title: "Day 3 — Into the fifties",
                      narration: "The sea has changed colour and the swell has doubled its length. The ship no longer sits still for anything. Brace yourself and swing the arc wide.",
                      seeds: daySeeds(203)),
            VoyageDay(title: "Day 5 — Snow squalls",
                      narration: "Squalls coming through every hour, each one shutting the sky like a door. You will get one clear gap. Be ready before it opens.",
                      seeds: daySeeds(205)),
            VoyageDay(title: "Day 7 — Off the Horn",
                      narration: "The land itself is somewhere under the murk to the north. The current sets east at two knots and the dead reckoning has been guessing for two days.",
                      seeds: daySeeds(207)),
            VoyageDay(title: "Day 9 — The gale eases",
                      narration: "First clear twilight in four days and the stars are out in numbers you will not see anywhere else on Earth. Take three. Take four if you can.",
                      seeds: daySeeds(209)),
            VoyageDay(title: "Day 11 — Standing north-east",
                      narration: "Round, and the ship is standing up to the Falklands with a following sea. The horizon is high and hard between the swells.",
                      seeds: daySeeds(211)),
            VoyageDay(title: "Day 13 — Kelp and cliffs",
                      narration: "Kelp on the surface means shoal water is not far off. The chart out here was drawn by men in worse ships than yours and it is not to be trusted absolutely.",
                      seeds: daySeeds(213)),
            VoyageDay(title: "Day 14 — Into Stanley",
                      narration: "One more fix before the entrance. The passage in is narrow and there is nothing forgiving about the rocks on either hand.",
                      seeds: daySeeds(214)),
           ]),

    Voyage(slug: "iceedge", name: "The Ice Edge",
           subtitle: "Reykjavik to Cape Farewell", era: "1904", miles: 720,
           opening: "A short passage on paper and a long one in fact. Ice to the north, fog on the bank, and a horizon that some days simply is not there.",
           arrival: "Cape Farewell showed itself for eleven minutes between two fog banks, which was enough. Down here that counts as a generous landfall.",
           days: [
            VoyageDay(title: "Day 1 — Out of Faxafloi",
                      narration: "Iceland astern in clear cold air. Make the most of it: this is the last unambiguous horizon you are likely to get for a week.",
                      seeds: daySeeds(301)),
            VoyageDay(title: "Day 2 — The bank",
                      narration: "Fog on the bank, thick enough to hide the bow. No sights today. Everything now rests on the log and the compass and the man on the wheel.",
                      seeds: daySeeds(302)),
            VoyageDay(title: "Day 3 — A gap in the fog",
                      narration: "A hole has opened overhead and the horizon is showing to the south. Whatever you can get in the next twenty minutes is what you have.",
                      seeds: daySeeds(303)),
            VoyageDay(title: "Day 4 — Ice blink",
                      narration: "A white glare along the northern sky — light thrown up off pack ice below the horizon. It is a warning, and it is also the only thing telling you where north is today.",
                      seeds: daySeeds(304)),
            VoyageDay(title: "Day 5 — Growlers",
                      narration: "Low ice in the water, hard to see and hard on a hull. The ship has slowed to steerage way and the position matters more with every hour.",
                      seeds: daySeeds(305)),
            VoyageDay(title: "Day 6 — Clear and bitter",
                      narration: "Minus fourteen on deck and the sky like polished glass. Cold air is honest air: refraction is behaving and the stars are as steady as they ever get.",
                      seeds: daySeeds(306)),
            VoyageDay(title: "Day 7 — The current sets south",
                      narration: "The East Greenland current has been carrying you south for three days and the log knows nothing about it. Only the sky can catch a current.",
                      seeds: daySeeds(307)),
            VoyageDay(title: "Day 8 — Farewell",
                      narration: "The cape should be forty miles on the starboard bow. In this visibility you will see it at eight. The margin between those two numbers is your entire evening.",
                      seeds: daySeeds(308)),
           ]),

    Voyage(slug: "monsoon", name: "The Monsoon Run",
           subtitle: "Zanzibar to Cochin", era: "1868", miles: 2400,
           opening: "The oldest trade route that navigation ever served. Go with the south-west monsoon or do not go at all — and the wind will not wait past September.",
           arrival: "The Malabar coast came out of the haze exactly at the hour the reckoning promised. Fifteen hundred years of dhow captains made this crossing without a sextant at all, which is a humbling thought to carry ashore.",
           days: [
            VoyageDay(title: "Day 1 — Clear of the channel",
                      narration: "Out past the reef with the monsoon on the beam. Warm, wet air and a horizon that will be soft for most of this passage.",
                      seeds: daySeeds(401)),
            VoyageDay(title: "Day 3 — The wind hardens",
                      narration: "The monsoon has come in strong and the ship is burying her lee rail. Getting a steady sight from this deck is half the work.",
                      seeds: daySeeds(403)),
            VoyageDay(title: "Day 6 — Crossing the line",
                      narration: "The equator, and the whole sky changes hands. Both poles are on the horizon and none of the old northern habits help you now.",
                      seeds: daySeeds(406)),
            VoyageDay(title: "Day 9 — Squall lines",
                      narration: "Black walls of rain marching across from the south-west, each one shutting down the horizon for an hour. Work between them.",
                      seeds: daySeeds(409)),
            VoyageDay(title: "Day 12 — Flat calm",
                      narration: "The wind has gone entirely and the sea is a mirror. A perfect deck for sights, and no way at all of getting anywhere with them.",
                      seeds: daySeeds(412)),
            VoyageDay(title: "Day 15 — Haze and heat",
                      narration: "The air is thick enough to see. The horizon is a suggestion rather than a line, and every altitude tonight wants taking twice.",
                      seeds: daySeeds(415)),
            VoyageDay(title: "Day 18 — Fishermen",
                      narration: "Small craft on the water, forty miles from anywhere they could have come from without a good idea of where they are. The coast is ahead.",
                      seeds: daySeeds(418)),
            VoyageDay(title: "Day 20 — The Malabar coast",
                      narration: "Low green land and a river mouth somewhere in it. The approach is shallow and the last fix decides whether you enter tonight or stand off till dawn.",
                      seeds: daySeeds(420)),
           ]),
]

let voyagesB: [Voyage] = [
    Voyage(slug: "greatcircle", name: "The Great Circle",
           subtitle: "Yokohama to San Francisco", era: "1889", miles: 4530,
           opening: "The shortest way across is a curve that looks wrong on every chart. North almost into the Aleutians, then down. Colder, rougher, and eight hundred miles less.",
           arrival: "The Farallones first, then the gate itself. Four thousand five hundred miles on a track that never looked straight and never was.",
           days: [
            VoyageDay(title: "Day 1 — Out past Oshima",
                      narration: "Japan astern and the great circle track already bending north. On the chart it looks like a mistake. On the globe it is the only sensible line.",
                      seeds: daySeeds(501)),
            VoyageDay(title: "Day 5 — The Kuroshio",
                      narration: "A warm current setting north-east at three knots, and warm water under cold air makes a horizon that lies. Expect your sights to scatter.",
                      seeds: daySeeds(505)),
            VoyageDay(title: "Day 10 — Fog on the northern leg",
                      narration: "Grey on grey for four days. The track is at its most northerly here, which is also where it is least visible.",
                      seeds: daySeeds(510)),
            VoyageDay(title: "Day 14 — The turn",
                      narration: "The highest latitude of the passage, and from here it is all south-east. A clear night at last and stars enough to be choosy.",
                      seeds: daySeeds(514)),
            VoyageDay(title: "Day 18 — Gales from the west",
                      narration: "Following sea, and the ship yawing thirty degrees either side of her course. The log is a work of fiction until this weather passes.",
                      seeds: daySeeds(518)),
            VoyageDay(title: "Day 22 — Steady again",
                      narration: "The North Pacific high has spread over you and the weather has gone quiet. Long clear twilights and a hard rim. Take everything you can.",
                      seeds: daySeeds(522)),
            VoyageDay(title: "Day 26 — The coastal fog",
                      narration: "The California fog bank is out there somewhere and once you are inside it you will see nothing at all until the horn sounds.",
                      seeds: daySeeds(526)),
            VoyageDay(title: "Day 28 — Making the gate",
                      narration: "The Farallones ought to be dead ahead at twenty miles. There is no room for a twenty-mile error on this coast.",
                      seeds: daySeeds(528)),
           ]),

    Voyage(slug: "bight", name: "The Great Bight",
           subtitle: "Fremantle to Adelaide", era: "1911", miles: 1420,
           opening: "A thousand miles of cliff with nothing behind it and nothing in front. No harbours, no lights, no help. The southern ocean comes at the Bight without meeting anything else first.",
           arrival: "Kangaroo Island abeam and the gulf opening ahead. The Bight is not a difficult passage. It is simply one that does not forgive.",
           days: [
            VoyageDay(title: "Day 1 — South about",
                      narration: "Round Cape Leeuwin with the swell on the beam. From here the coast runs east and there is nothing to leeward but limestone cliff.",
                      seeds: daySeeds(601)),
            VoyageDay(title: "Day 3 — The long cliffs",
                      narration: "Eighty miles of unbroken cliff on the port hand, all of it identical. Bearings are useless here. Only the sky can tell you which part you are looking at.",
                      seeds: daySeeds(603)),
            VoyageDay(title: "Day 5 — A southerly buster",
                      narration: "The wind has come round hard to the south and the sea with it. Cold clear air behind the front, though — the stars will be worth having tonight.",
                      seeds: daySeeds(605)),
            VoyageDay(title: "Day 7 — The middle of it",
                      narration: "Nothing on the chart within two hundred miles. This is the stretch where a navigator finds out what their own arithmetic is worth.",
                      seeds: daySeeds(607)),
            VoyageDay(title: "Day 9 — Whale season",
                      narration: "Southern rights on the water, come up from the ice to calve. A quiet day, a flat deck, and no excuse whatever for a poor sight.",
                      seeds: daySeeds(609)),
            VoyageDay(title: "Day 11 — Dust from the north",
                      narration: "Red dust off the interior, carried out a hundred miles. The sun goes down the colour of an old penny and the horizon disappears an hour early.",
                      seeds: daySeeds(611)),
            VoyageDay(title: "Day 13 — Nearing the gulfs",
                      narration: "The coast begins to break up at last. Islands ahead, and with them the first chance of a bearing that means something.",
                      seeds: daySeeds(613)),
            VoyageDay(title: "Day 14 — Into the gulf",
                      narration: "Backstairs Passage is narrow, the tide runs hard through it, and it must be entered on the right side of the island. One last fix.",
                      seeds: daySeeds(614)),
           ]),

    Voyage(slug: "doldrums", name: "The Doldrums Passage",
           subtitle: "Freetown to Recife", era: "1841", miles: 1860,
           opening: "Across the belt of calms that lies on the equator like a wall. Ships have sat in it for three weeks, boiling, going nowhere, with a perfect sky overhead every single night.",
           arrival: "The Brazilian coast, low and green, after eleven days of doing nothing and eight of doing everything. The crossing is not hard. The waiting is.",
           days: [
            VoyageDay(title: "Day 1 — Standing south-west",
                      narration: "Out of the river with the last of the land breeze. The trade will carry you as far as the calms and no further.",
                      seeds: daySeeds(701)),
            VoyageDay(title: "Day 4 — The trade dies",
                      narration: "The wind has gone light and fitful and the sails are slatting. Ahead lies the belt. Fix yourself properly before you enter it.",
                      seeds: daySeeds(704)),
            VoyageDay(title: "Day 6 — Flat calm, thunder",
                      narration: "No wind and a black anvil of cloud in every quarter. The horizon between the squalls is like glass and the sights are the finest you will ever take.",
                      seeds: daySeeds(706)),
            VoyageDay(title: "Day 9 — Drifting",
                      narration: "Nine miles made good in a day, all of it current. The log records nothing. Only the sky knows the ship has moved at all.",
                      seeds: daySeeds(709)),
            VoyageDay(title: "Day 12 — Crossing the line",
                      narration: "Somewhere in this hot silence the ship has changed hemispheres. The southern stars are up and the northern ones are going down astern.",
                      seeds: daySeeds(712)),
            VoyageDay(title: "Day 15 — The south-east trade",
                      narration: "Wind at last, hard on the bow. The ship heels and the horizon starts jumping about again. You had grown used to the calm.",
                      seeds: daySeeds(715)),
            VoyageDay(title: "Day 18 — The current sets west",
                      narration: "The South Equatorial Current is running strong and setting you toward the corner of Brazil rather faster than the reckoning allows for.",
                      seeds: daySeeds(718)),
            VoyageDay(title: "Day 20 — Cabo Branco",
                      narration: "The easternmost corner of the continent lies ahead and there is a reef off it. Know your longitude tonight or stand off until you do.",
                      seeds: daySeeds(720)),
           ]),

    Voyage(slug: "baltic", name: "The Winter Baltic",
           subtitle: "Gdansk to Stockholm", era: "1896", miles: 380,
           opening: "Short, shallow, crowded and frozen. Four hours of usable daylight, ice in the fairway, and a sky that shows itself perhaps twice a week.",
           arrival: "The archipelago at last, and a pilot who did not ask how you had found your way there. Which was just as well.",
           days: [
            VoyageDay(title: "Day 1 — Out of the bay",
                      narration: "Grey water, grey sky, three hours of light. Take what the sky offers the moment it offers it.",
                      seeds: daySeeds(801)),
            VoyageDay(title: "Day 2 — Snow",
                      narration: "Snow all day and the deck a skating rink. The horizon closed at noon and did not reopen. Dead reckoning, then, and hope.",
                      seeds: daySeeds(802)),
            VoyageDay(title: "Day 3 — A clear afternoon",
                      narration: "The sky opened for two hours in the afternoon and the Sun was low enough to shoot without a shade. Refraction down there is a liar, so take several.",
                      seeds: daySeeds(803)),
            VoyageDay(title: "Day 4 — Ice in the fairway",
                      narration: "Drift ice coming down from the north and the ship picking her way through it. Position matters now to the half mile.",
                      seeds: daySeeds(804)),
            VoyageDay(title: "Day 5 — Gotland abeam",
                      narration: "The light on the southern point, first thing seen in three days that has a name. Check your reckoning against it and see how badly you were doing.",
                      seeds: daySeeds(805)),
            VoyageDay(title: "Day 6 — A hard frost, clear night",
                      narration: "Twelve hours of darkness and not a cloud in it. This is why the winter Baltic is not entirely hopeless: when it clears, it clears completely.",
                      seeds: daySeeds(806)),
            VoyageDay(title: "Day 7 — Approaching the skerries",
                      narration: "Ten thousand islands ahead, most of them unmarked, all of them granite. The archipelago is no place to arrive uncertain.",
                      seeds: daySeeds(807)),
            VoyageDay(title: "Day 8 — Sandhamn",
                      narration: "The pilot station is somewhere in that maze of rock. One last fix, taken in eleven minutes of grey afternoon, and then it is somebody else's problem.",
                      seeds: daySeeds(808)),
           ]),
]
